use minifb::Key;

pub fn key_to_code(key: Key) -> Option<u32> {
    Some(match key {
        Key::A => 1,
        Key::B => 2,
        Key::C => 3,
        Key::D => 4,
        Key::E => 5,
        Key::F => 6,
        Key::G => 7,
        Key::H => 8,
        Key::I => 9,
        Key::J => 10,
        Key::K => 11,
        Key::L => 12,
        Key::M => 13,
        Key::N => 14,
        Key::O => 15,
        Key::P => 16,
        Key::Q => 17,
        Key::R => 18,
        Key::S => 19,
        Key::T => 20,
        Key::U => 21,
        Key::V => 22,
        Key::W => 23,
        Key::X => 24,
        Key::Y => 25,
        Key::Z => 26,
        Key::Key0 => 30,
        Key::Key1 => 31,
        Key::Key2 => 32,
        Key::Key3 => 33,
        Key::Key4 => 34,
        Key::Key5 => 35,
        Key::Key6 => 36,
        Key::Key7 => 37,
        Key::Key8 => 38,
        Key::Key9 => 39,
        Key::Space => 40,
        Key::Enter => 41,
        Key::Backspace => 42,
        Key::Tab => 43,
        Key::Left => 44,
        Key::Right => 45,
        Key::Up => 46,
        Key::Down => 47,
        Key::LeftShift => 48,
        Key::LeftCtrl => 49,
        Key::LeftAlt => 50,
        _ => return None,
    })
}

pub fn code_to_key(code: u32) -> Option<Key> {
    Some(match code {
        1 => Key::A,
        2 => Key::B,
        3 => Key::C,
        4 => Key::D,
        5 => Key::E,
        6 => Key::F,
        7 => Key::G,
        8 => Key::H,
        9 => Key::I,
        10 => Key::J,
        11 => Key::K,
        12 => Key::L,
        13 => Key::M,
        14 => Key::N,
        15 => Key::O,
        16 => Key::P,
        17 => Key::Q,
        18 => Key::R,
        19 => Key::S,
        20 => Key::T,
        21 => Key::U,
        22 => Key::V,
        23 => Key::W,
        24 => Key::X,
        25 => Key::Y,
        26 => Key::Z,
        30 => Key::Key0,
        31 => Key::Key1,
        32 => Key::Key2,
        33 => Key::Key3,
        34 => Key::Key4,
        35 => Key::Key5,
        36 => Key::Key6,
        37 => Key::Key7,
        38 => Key::Key8,
        39 => Key::Key9,
        40 => Key::Space,
        41 => Key::Enter,
        42 => Key::Backspace,
        43 => Key::Tab,
        44 => Key::Left,
        45 => Key::Right,
        46 => Key::Up,
        47 => Key::Down,
        48 => Key::LeftShift,
        49 => Key::LeftCtrl,
        50 => Key::LeftAlt,
        _ => return None,
    })
}
