// This file has been generated by Specta. Do not edit this file manually.
export type AccountResponse = {
	email: string,
};

export type ApiError = {
	error: string,
};

export type AuthLoginRequest = {
	email: string,
	password: string,
};

export type AuthLogoutRequest = {
	refresh_token: string,
};

export type AuthRefreshRequest = {
	refresh_token: string,
};

export type AuthRegisterRequest = {
	email: string,
	password: string,
};

export type AuthResponse = {
	token: string,
	refresh_token: string,
};

/**  Unique identifier for a registered device. */
export type DeviceId = string;

export type DeviceInfo = {
	device_id: DeviceId,
	name: string,
	iroh_public_key: string,
	enabled_features: FeatureId[],
	last_seen: string | null,
	online: boolean,
};

export type DeviceListResponse = {
	devices: DeviceInfo[],
};

/**  Update server-managed device policy (`name`, `enabled_features`). */
export type DevicePatchRequest = {
	name: string | null,
	enabled_features: FeatureId[] | null,
};

/**
 *  Create or update a device's transport registration.
 * 
 *  On create, all fields are stored. On update, the server only applies
 *  `iroh_public_key` and `last_seen`; use [`DevicePatchRequest`] to change
 *  `name` or `enabled_features`.
 */
export type DeviceUpsertRequest = {
	device_id: DeviceId,
	name: string,
	iroh_public_key: string,
	enabled_features: FeatureId[],
};

/**  Identifies a sync feature */
export type FeatureId = "clipboard" | "shell" | "port_forward" | "file_send";

export type PairingCreateResponse = {
	code: string,
	expires_at: string,
};

export type PairingRedeemRequest = {
	code: string,
	device: DeviceUpsertRequest | null,
};
